name: publish-tool

on: [workflow_dispatch]

env:
  GHCR: ghcr.io

jobs:
  tool:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine version
        run: echo "PIPECD_VERSION=$(git describe --tags --always --abbrev=7)" >> $GITHUB_ENV

      # Login to push container images.
      - name: Log in to the container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b #v2.0.0
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Building and pushing container images.
      - name: Build and push piped-base image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: tool/piped-base
          tags: ${{ env.GHCR }}/kentakozuka/piped-base:${{ env.PIPECD_VERSION }}
          push: true